name: Build and deploy Jekyll site to GitHub Pages

defaults:
  run:
    shell: bash


on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-16.04
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
        with:
          ref: master

      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/assets/images/*
          key: ${{ runner.os }}-${{ hashFiles('~/assets/images/') }}

      - name: Install ImageMagick and LibVips
        run: sudo apt-get install imagemagick libvips
      
      - name: Install Webp
        run: curl -s https://raw.githubusercontent.com/Intervox/node-webp/latest/bin/install_webp | sudo bash
      
      - name: Install NPM dependencies
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      
      - name: Install gems and deploy
        run: |
          bundle install
          JEKYLL_ENV=production jekyll build
      
      - name: Generate Critical
        run: |
          make critical
          JEKYLL_ENV=production jekyll build          
      
      - name: Commit
        run: |
          cd _site
          git init
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add changes" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.JEKYLL_PAT }}
          branch: page
          force: true
          directory: _site


      
      
